declare let op1: string, op2: string, opr: string, perform: string, flag: boolean, dot: boolean, performFlg: boolean, DOMdisp: HTMLElement, DOMwhlStr: HTMLElement, DOMselTrigo: HTMLOptionElement;
declare function btnpress(val: any): void;
declare function btnOpration(opration: any): void;
declare function getAns(): void;
declare function reset(): void;
declare function btnClear(): void;
declare function btnDel(): void;
declare function btnAbs(): void;
declare function changesign(): void;
declare function btnFactorial(): void;
declare function btnPie(): void;
declare function btnLog(): void;
declare function btnLn(): void;
declare function btnPower(): void;
declare function btnPower10(): void;
declare function btnPower_xy(): number;
declare function btnSqrt(): void;
declare function btnInverse(): void;
declare function btnE(): void;
declare function btnExpo(): void;
declare function Trigo(text: string): void;
